# coverage:
#   status:
#     project:
#       default:
#         threshold: 50%
#         target: 50%

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
#comment: false
